In [4]:
import pandas as pd
import numpy as np

In [5]:
df = pd.read_csv("adult_new.csv")

In [6]:
df

age         workclass  fnlwgt     education  educational-num  \
0       28         Local-gov  336951    Assoc-acdm               12   
1       44           Private  160323  Some-college               10   
2       63  Self-emp-not-inc  104626   Prof-school               15   
3       65           Private  184454       HS-grad                9   
4       48           Private  279724       HS-grad                9   
...    ...               ...     ...           ...              ...   
27409   27           Private  257302    Assoc-acdm               12   
27410   40           Private  154374       HS-grad                9   
27411   58           Private  151910       HS-grad                9   
27412   22           Private  201490       HS-grad                9   
27413   52      Self-emp-inc  287927       HS-grad                9   

           marital-status         occupation relationship   race  gender  \
0      Married-civ-spouse    Protective-serv      Husband  White    Male   
1      Married-civ-spouse  Machine-op-inspct      Husband  Black    Male   
2      Married-civ-spouse     Prof-specialty      Husband  White    Male   
3      Married-civ-spouse  Machine-op-inspct      Husband  White    Male   
4      Married-civ-spouse  Machine-op-inspct      Husband  White    Male   
...                   ...                ...          ...    ...     ...   
27409  Married-civ-spouse       Tech-support         Wife  White  Female   
27410  Married-civ-spouse  Machine-op-inspct      Husband  White    Male   
27411             Widowed       Adm-clerical    Unmarried  White  Female   
27412       Never-married       Adm-clerical    Own-child  White    Male   
27413  Married-civ-spouse    Exec-managerial         Wife  White  Female   

       capital-gain  capital-loss  hours-per-week native-country income  
0                 0             0              40  United-States   >50K  
1              7688             0              40  United-States   >50K  
2              3103             0              32  United-States   >50K  
3              6418             0              40  United-States   >50K  
4              3103             0              48  United-States   >50K  
...             ...           ...             ...            ...    ...  
27409             0             0              38  United-States  <=50K  
27410             0             0              40  United-States   >50K  
27411             0             0              40  United-States  <=50K  
27412             0             0              20  United-States  <=50K  
27413         15024             0              40  United-States   >50K  

[27414 rows x 15 columns]

In [7]:
df["income"].unique()

array(['>50K', '<=50K'], dtype=object)

In [8]:
df.isnull().sum()

age                0
workclass          0
fnlwgt             0
education          0
educational-num    0
marital-status     0
occupation         0
relationship       0
race               0
gender             0
capital-gain       0
capital-loss       0
hours-per-week     0
native-country     0
income             0
dtype: int64

In [9]:
for i in df:
    print("Column names:",i,df[i].unique())
    

Column names: age [28 44 63 65 48 43 40 34 45 46 36 22 42 41 55 33 59 29 27 31 58 54 37 56
 39 51 50 52 47 24 64 53 35 32 30 68 57 66 49 38 61 73 26 23 25 62 90 60
 67 69 72 85 71 77 70 19 21 74 75 20 81 76 80 88 78 79 84 17 18 82 83 86
 87]
Column names: workclass ['Local-gov' 'Private' 'Self-emp-not-inc' 'State-gov' 'Self-emp-inc' '?'
 'Federal-gov' 'Without-pay' 'Never-worked']
Column names: fnlwgt [336951 160323 104626 ...  84661 310152 257302]
Column names: education ['Assoc-acdm' 'Some-college' 'Prof-school' 'HS-grad' 'Masters' 'Doctorate'
 'Bachelors' 'Assoc-voc' '9th' '10th' '7th-8th' '11th' '5th-6th' '1st-4th'
 '12th' 'Preschool']
Column names: educational-num [12 10 15  9 14 16 13 11  5  6  4  7  3  2  8  1]
Column names: marital-status ['Married-civ-spouse' 'Never-married' 'Divorced' 'Separated'
 'Married-AF-spouse' 'Widowed' 'Married-spouse-absent']
Column names: occupation ['Protective-serv' 'Machine-op-inspct' 'Prof-specialty' 'Exec-managerial'
 'Tech-support' 'Craft-repa

In [10]:
#another way
for i in df.columns:
    print(f"Unique values in column {i}:\n\n{df[i].unique()}\n")

Unique values in column age:

[28 44 63 65 48 43 40 34 45 46 36 22 42 41 55 33 59 29 27 31 58 54 37 56
 39 51 50 52 47 24 64 53 35 32 30 68 57 66 49 38 61 73 26 23 25 62 90 60
 67 69 72 85 71 77 70 19 21 74 75 20 81 76 80 88 78 79 84 17 18 82 83 86
 87]

Unique values in column workclass:

['Local-gov' 'Private' 'Self-emp-not-inc' 'State-gov' 'Self-emp-inc' '?'
 'Federal-gov' 'Without-pay' 'Never-worked']

Unique values in column fnlwgt:

[336951 160323 104626 ...  84661 310152 257302]

Unique values in column education:

['Assoc-acdm' 'Some-college' 'Prof-school' 'HS-grad' 'Masters' 'Doctorate'
 'Bachelors' 'Assoc-voc' '9th' '10th' '7th-8th' '11th' '5th-6th' '1st-4th'
 '12th' 'Preschool']

Unique values in column educational-num:

[12 10 15  9 14 16 13 11  5  6  4  7  3  2  8  1]

Unique values in column marital-status:

['Married-civ-spouse' 'Never-married' 'Divorced' 'Separated'
 'Married-AF-spouse' 'Widowed' 'Married-spouse-absent']

Unique values in column occupation:

['Protectiv

In [11]:
df.replace("?",np.nan,inplace=True)

In [12]:
df.isnull().sum()

age                   0
workclass          1283
fnlwgt                0
education             0
educational-num       0
marital-status        0
occupation         1288
relationship          0
race                  0
gender                0
capital-gain          0
capital-loss          0
hours-per-week        0
native-country      508
income                0
dtype: int64

In [13]:
df["workclass"].unique()

array(['Local-gov', 'Private', 'Self-emp-not-inc', 'State-gov',
       'Self-emp-inc', nan, 'Federal-gov', 'Without-pay', 'Never-worked'],
      dtype=object)

In [14]:
df["workclass"].mode() 

0    Private
Name: workclass, dtype: object

In [15]:
df["workclass"].fillna(df["workclass"].mode()[0],inplace=True)

In [16]:
df["occupation"].fillna(df["occupation"].mode()[0],inplace=True)

In [17]:
df["native-country"].fillna(df["native-country"].mode()[0],inplace=True)

In [18]:
df.isnull().sum()

age                0
workclass          0
fnlwgt             0
education          0
educational-num    0
marital-status     0
occupation         0
relationship       0
race               0
gender             0
capital-gain       0
capital-loss       0
hours-per-week     0
native-country     0
income             0
dtype: int64

In [19]:
df.dtypes

age                 int64
workclass          object
fnlwgt              int64
education          object
educational-num     int64
marital-status     object
occupation         object
relationship       object
race               object
gender             object
capital-gain        int64
capital-loss        int64
hours-per-week      int64
native-country     object
income             object
dtype: object

In [20]:
#Another way to fill the null  values
for i in df.columns:
    if df[i].dtypes == "object":
        df[i].fillna(df[i].mode()[0],inplace=True)
    else:
        df[i].fillna(df[i].mean(),inplace=True)

In [21]:
df.isnull().sum()

age                0
workclass          0
fnlwgt             0
education          0
educational-num    0
marital-status     0
occupation         0
relationship       0
race               0
gender             0
capital-gain       0
capital-loss       0
hours-per-week     0
native-country     0
income             0
dtype: int64

In [35]:
#Getting all the categorical columns
cat_col=[]
for x in df.columns:
   if df[x].dtypes == 'object':
       cat_col.append(x)
cat_col

['workclass',
 'education',
 'marital-status',
 'occupation',
 'relationship',
 'race',
 'gender',
 'native-country',
 'income']

In [43]:
#Converting the categorical value to numeric value using LabelEncoder
from sklearn.preprocessing import LabelEncoder

le = LabelEncoder()
for x in cat_col:
    df[x] = le.fit_transform(df[x])
    
    le_name_mapping = dict(zip(le.classes_ , le.transform(le.classes_)))
    print('Feature',x)
    print('Mapping',le_name_mapping)

Feature workclass
Mapping {0: 0, 1: 1, 2: 2, 3: 3, 4: 4, 5: 5, 6: 6, 7: 7}
Feature education
Mapping {0: 0, 1: 1, 2: 2, 3: 3, 4: 4, 5: 5, 6: 6, 7: 7, 8: 8, 9: 9, 10: 10, 11: 11, 12: 12, 13: 13, 14: 14, 15: 15}
Feature marital-status
Mapping {0: 0, 1: 1, 2: 2, 3: 3, 4: 4, 5: 5, 6: 6}
Feature occupation
Mapping {0: 0, 1: 1, 2: 2, 3: 3, 4: 4, 5: 5, 6: 6, 7: 7, 8: 8, 9: 9, 10: 10, 11: 11, 12: 12, 13: 13}
Feature relationship
Mapping {0: 0, 1: 1, 2: 2, 3: 3, 4: 4, 5: 5}
Feature race
Mapping {0: 0, 1: 1, 2: 2, 3: 3, 4: 4}
Feature gender
Mapping {0: 0, 1: 1}
Feature native-country
Mapping {0: 0, 1: 1, 2: 2, 3: 3, 4: 4, 5: 5, 6: 6, 7: 7, 8: 8, 9: 9, 10: 10, 11: 11, 12: 12, 13: 13, 14: 14, 15: 15, 16: 16, 17: 17, 18: 18, 19: 19, 20: 20, 21: 21, 22: 22, 23: 23, 24: 24, 25: 25, 26: 26, 27: 27, 28: 28, 29: 29, 30: 30, 31: 31, 32: 32, 33: 33, 34: 34, 35: 35, 36: 36, 37: 37, 38: 38, 39: 39, 40: 40}
Feature income
Mapping {0: 0, 1: 1}


In [38]:
df

age  workclass  fnlwgt  education  educational-num  marital-status  \
0       28          1  336951          7               12               2   
1       44          3  160323         15               10               2   
2       63          5  104626         14               15               2   
3       65          3  184454         11                9               2   
4       48          3  279724         11                9               2   
...    ...        ...     ...        ...              ...             ...   
27409   27          3  257302          7               12               2   
27410   40          3  154374         11                9               2   
27411   58          3  151910         11                9               6   
27412   22          3  201490         11                9               4   
27413   52          4  287927         11                9               2   

       occupation  relationship  race  gender  capital-gain  capital-loss  \
0              10             0     4       1             0             0   
1               6             0     2       1          7688             0   
2               9             0     4       1          3103             0   
3               6             0     4       1          6418             0   
4               6             0     4       1          3103             0   
...           ...           ...   ...     ...           ...           ...   
27409          12             5     4       0             0             0   
27410           6             0     4       1             0             0   
27411           0             4     4       0             0             0   
27412           0             3     4       1             0             0   
27413           3             5     4       0         15024             0   

       hours-per-week  native-country  income  
0                  40              38       1  
1                  40              38       1  
2                  32              38       1  
3                  40              38       1  
4                  48              38       1  
...               ...             ...     ...  
27409              38              38       0  
27410              40              38       1  
27411              40              38       0  
27412              20              38       0  
27413              40              38       1  

[27414 rows x 15 columns]

In [44]:
#Identify independent variable
x = df.iloc[:,:-1]

In [45]:
#Dependent variable
y=df.iloc[:,-1]

In [50]:
x.shape

(27414, 14)

In [51]:
y.shape

(27414,)

In [52]:
from sklearn.model_selection import train_test_split

In [59]:
x_train , x_test , y_train,y_test = train_test_split(x,y,test_size=0.25,random_state=42)

In [60]:
print("X Train",x_train.shape)
print("Y Train",y_train.shape)
print("X Test",x_test.shape)
print("Y Train",x_test.shape)

X Train (20560, 14)
Y Train (20560,)
X Test (6854, 14)
Y Train (6854, 14)


In [62]:
from sklearn.linear_model import LogisticRegression

In [63]:
classifier = LogisticRegression()

In [64]:
classifier.fit(x_train,y_train)

LogisticRegression()

In [66]:
y_pred = classifier.predict(x_test)
print(y_pred)
print(list(zip(y_test,y_pred)))

[0 0 0 ... 0 0 1]
[(0, 0), (0, 0), (1, 0), (0, 0), (0, 0), (0, 0), (0, 0), (0, 0), (0, 0), (1, 1), (0, 0), (0, 1), (0, 0), (1, 0), (1, 1), (0, 0), (0, 0), (0, 0), (0, 0), (0, 0), (0, 0), (1, 0), (0, 0), (0, 0), (0, 0), (0, 0), (1, 1), (1, 1), (0, 0), (0, 0), (0, 0), (0, 0), (1, 0), (1, 0), (1, 0), (1, 0), (0, 0), (0, 0), (1, 0), (1, 0), (1, 0), (0, 0), (0, 0), (0, 0), (0, 0), (0, 0), (1, 0), (0, 0), (0, 1), (1, 1), (0, 0), (1, 0), (0, 0), (0, 0), (1, 1), (0, 0), (1, 0), (0, 0), (0, 0), (0, 0), (0, 0), (1, 0), (1, 0), (0, 0), (0, 0), (0, 0), (0, 0), (1, 0), (1, 0), (1, 0), (1, 1), (1, 0), (0, 0), (0, 0), (1, 0), (0, 0), (1, 0), (0, 0), (0, 0), (0, 0), (1, 0), (0, 0), (1, 1), (0, 0), (1, 0), (1, 0), (0, 0), (0, 0), (1, 1), (1, 0), (0, 0), (1, 1), (1, 0), (1, 1), (1, 0), (0, 0), (1, 0), (1, 0), (0, 0), (0, 0), (1, 1), (0, 0), (1, 0), (1, 1), (1, 1), (1, 1), (1, 1), (0, 0), (1, 0), (1, 1), (0, 0), (1, 0), (0, 0), (1, 0), (0, 0), (0, 0), (0, 0), (0, 0), (0, 0), (1, 0), (1, 0), (0, 0), (0, 0

In [67]:
from sklearn.metrics import accuracy_score,classification_report,confusion_matrix

In [69]:
print(accuracy_score(y_test,y_pred))
print("CLASSIFICATION REPORT",classification_report(y_test,y_pred))
print(confusion_matrix(y_test,y_pred))

0.66836883571637
CLASSIFICATION REPORT               precision    recall  f1-score   support

           0       0.64      0.94      0.76      3901
           1       0.80      0.31      0.45      2953

    accuracy                           0.67      6854
   macro avg       0.72      0.62      0.60      6854
weighted avg       0.71      0.67      0.63      6854

[[3665  236]
 [2037  916]]
